name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            checks: write
            contents: write
            security-events: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Install OpenGL dependencies
              run: sudo apt-get install -y xvfb libgl1-mesa-dev

            - name: Run checks
              run: xvfb-run ./gradlew check
              env:
                  LIBGL_ALWAYS_SOFTWARE: "1"

            -   name: Upload Detekt results
                uses: github/codeql-action/upload-sarif@v3
                if: always()
                with:
                    sarif_file: ${{ github.workspace }}
                    category: detekt

            -   name: Test Report
                uses: dorny/test-reporter@v1
                if: always()
                with:
                    name: Tests
                    path: '**/build/test-results/test/*.xml'
                    reporter: java-junit

            -   name: Generate Coverage Badge
                uses: cicirello/jacoco-badge-generator@v2
                with:
                    jacoco-csv-file: build/reports/jacoco/jacocoAggregatedReport/jacocoAggregatedReport.csv

            -   name: Commit Badge
                uses: stefanzweifel/git-auto-commit-action@v5
                with:
                    commit_message: "Update coverage badge"
                    file_pattern: ".github/badges/*.svg"
